brew "bash-completion"
brew "coreutils"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "jq"
brew "nmap"
brew "pyenv-virtualenv"
brew "python"
brew "readline"
brew "ssh-copy-id"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"

cask "hammerspoon"
