# use brew to get around https://github.com/aws/aws-cli/issues/7252
brew "awscli"

brew "coreutils"
brew "eza"
brew "fzf"
brew "gh"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "golangci-lint"
brew "jq"
brew "kubectl"
brew "neovim"
brew "node"
brew "readline"
brew "uv"

tap "hashicorp/tap"
brew "hashicorp/tap/terraform"
brew "ripgrep"
brew "shellcheck"
brew "starship"
brew "stylua"
brew "watch"
brew "wget"
brew "zoxide"
