# use brew to get around https://github.com/aws/aws-cli/issues/7252
brew "awscli"

brew "kubectl"
brew "coreutils"
brew "gh"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "golangci-lint"
brew "jq"
brew "python"
brew "readline"
brew "shellcheck"
brew "starship"
brew "watch"
brew "wget"
